export default {
    install: function (Vue, options) {
        options
        // 4. 添加实例方法
        Vue.prototype.$lny = {
            zodiac:[
                {
                    name:'Mouse',
                    chn:'鼠',
                    image:'mouse.png'
                },
                {
                    name:'Ox',
                    chn:'牛',
                    image:'ox.png'
                },
                {
                    name:'Tiger',
                    chn:'虎',
                    image:'tiger.png'
                },
                {
                    name:'Rabbit',
                    chn:'兔',
                    image:'rabbit.png'
                },
                {
                    name:'Dragon',
                    chn:'龙',
                    image:'dragon.png'
                },
                {
                    name:'Snake',
                    chn:'蛇',
                    image:'snake.png'
                },
                {
                    name:'Horse',
                    chn:'马',
                    image:'horse.png'
                },
                {
                    name:'Sheep',
                    chn:'羊',
                    image:'sheep.png'
                },
                {
                    name:'Monkey',
                    chn:'猴',
                    image:'monkey.png'
                },
                {
                    name:'Chicken',
                    chn:'鸡',
                    image:'chicken.png'
                },
                {
                    name:'Dog',
                    chn:'狗',
                    image:'dog.png'
                },
                {
                    name:'Pig',
                    chn:'猪',
                    image:'pig.png'
                },
            ]
        }
    }
}